name: Tecton Development CI/CD

on:
  push:
    branches: [ dev, prod ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: 
      name: Development    
    steps:
      - uses: actions/checkout@v3

      - name: Run tecton plan
        run: echo I am running tecton plan on development branch
    
  apply:
    needs: [plan]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Apply development
        run: echo I am running tecton apply in development environment
      