name: Tecton Development CI/CD

on:
  push:
    branches: [ dev ]
  # pull_request:
  #   branches: [ dev ]
  # workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tecton plan in DEV branch
        run: |
          echo "Running plan with DEV_API_KEY: ${{ secrets.DEV_API_KEY }}"
    
  apply:
    needs: [plan]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Apply development
        run: echo I am running tecton apply in development environment
      