name: tecton plan to Production CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: 
      name: Production    
    steps:
      - uses: actions/checkout@v3

      - name: Run tecton plan
        run: echo I am running tecton plan on main branch      

  apply:
    runs-on: ubuntu-latest
    needs: [plan]
    environment: 
      name: Production
    steps:
      - uses: actions/checkout@v3

      - name: Run tecton apply
        run: echo I am running tecton apply in Production environment        