name: tecton plan/apply to Production CI/CD

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tecton plan in MAIN branch
        run: |
          echo "Running plan with PROD_API_KEY: ${{ secrets.PROD_API_KEY }}"

  apply:
    runs-on: ubuntu-latest
    needs: [plan]
    environment: 
      name: Production
    steps:
      - uses: actions/checkout@v3

      - name: Run tecton apply
        run: echo I am running tecton apply in Production environment        